export type TextSource = 'gutenberg' | 'wikisource';

export interface CatalogueEntry {
  title: string;
  author: string;
  description: string;
  source: TextSource;
  gutenbergId?: number;
  wikisourceTitle?: string;
  /** Fetch and concatenate multiple individual Wikisource pages (for collected works with no index page) */
  wikisourceTitles?: string[];
  librivoxAudioUrl: string;
  /** Override search string passed to LibriVox API when the full title doesn't match */
  librivoxSearchTitle?: string;
  /** Hardcoded cover image URL — skips Open Library search when present */
  coverUrl?: string;
  /** Collection this book belongs to (sets books.collection and filters from general catalog) */
  collection?: string;
  /** BCP-47 language code of the ingested text — defaults to 'es' if omitted */
  language?: string;
}

export const CATALOGUE: CatalogueEntry[] = [
  {
    title: 'Lazarillo de Tormes',
    author: 'Anónimo',
    description: 'Novela picaresca anónima del siglo XVI, fundadora del género en la literatura española.',
    source: 'wikisource',
    wikisourceTitles: [
      'La vida de Lazarillo de Tormes y de sus fortunas y adversidades/Prólogo',
      'La vida de Lazarillo de Tormes y de sus fortunas y adversidades/Tratado primero',
      'La vida de Lazarillo de Tormes y de sus fortunas y adversidades/Tratado segundo',
      'La vida de Lazarillo de Tormes y de sus fortunas y adversidades/Tratado tercero',
      'La vida de Lazarillo de Tormes y de sus fortunas y adversidades/Tratado cuarto',
      'La vida de Lazarillo de Tormes y de sus fortunas y adversidades/Tratado quinto',
      'La vida de Lazarillo de Tormes y de sus fortunas y adversidades/Tratado sexto',
      'La vida de Lazarillo de Tormes y de sus fortunas y adversidades/Tratado séptimo',
    ],
    librivoxAudioUrl: 'https://librivox.org/lazarillo-de-tormes/',
  },
  {
    title: 'El Sombrero de Tres Picos',
    author: 'Pedro Antonio de Alarcón',
    description: 'Comedia costumbrista del siglo XIX basada en una historia popular andaluza.',
    source: 'gutenberg',
    gutenbergId: 29506,
    librivoxAudioUrl: 'https://librivox.org/el-sombrero-de-tres-picos-by-pedro-antonio-de-alarcon-y-ariza/',
    librivoxSearchTitle: 'Sombrero de Tres Picos',
  },
  {
    title: 'Leyendas',
    author: 'Gustavo Adolfo Bécquer',
    description: 'Colección de leyendas románticas del poeta y narrador sevillano del siglo XIX.',
    source: 'gutenberg',
    gutenbergId: 10814,
    librivoxAudioUrl: 'https://librivox.org/leyendas-by-gustavo-adolfo-becquer/',
  },
  {
    title: 'Don Juan Tenorio',
    author: 'José Zorrilla',
    description: 'Drama romántico en verso sobre el legendario seductor español.',
    source: 'gutenberg',
    gutenbergId: 5201,
    librivoxAudioUrl: 'https://librivox.org/don-juan-by-jose-zorrilla-y-moral/',
  },
  {
    title: 'Marianela',
    author: 'Benito Pérez Galdós',
    description: 'Novela social de Galdós que explora la belleza, la pobreza y el amor en la España rural.',
    source: 'gutenberg',
    gutenbergId: 48818,
    librivoxAudioUrl: 'https://librivox.org/marianela-by-benito-perez-galdos/',
  },
  {
    title: 'Doña Perfecta',
    author: 'Benito Pérez Galdós',
    description: 'Novela que denuncia el fanatismo religioso y la intolerancia en la España del siglo XIX.',
    source: 'gutenberg',
    gutenbergId: 15725,
    librivoxAudioUrl: 'https://librivox.org/dona-perfecta-by-benito-perez-galdos/',
  },
  {
    title: 'Niebla',
    author: 'Miguel de Unamuno',
    description: 'Nivola existencialista en la que el protagonista cuestiona su propia realidad ante su creador.',
    source: 'gutenberg',
    gutenbergId: 49836,
    librivoxAudioUrl: 'https://librivox.org/niebla-by-miguel-de-unamuno/',
  },
  {
    title: 'El Gaucho Martín Fierro',
    author: 'José Hernández',
    description: 'Poema épico gauchesco argentino, símbolo de la identidad nacional latinoamericana.',
    source: 'gutenberg',
    gutenbergId: 14765,
    librivoxAudioUrl: 'https://librivox.org/el-gaucho-martin-fierro-by-jose-hernandez/',
    librivoxSearchTitle: 'Martin Fierro',
  },
  {
    title: 'Cuentos de Amor de Locura y de Muerte',
    author: 'Horacio Quiroga',
    description: 'Cuentos del maestro rioplatense del género, ambientados en la selva misionera.',
    source: 'gutenberg',
    gutenbergId: 13507,
    librivoxAudioUrl: 'https://librivox.org/cuentos-de-amor-de-locura-y-de-muerte-by-horacio-quiroga/',
  },
  {
    title: 'Los Cuatro Jinetes del Apocalipsis',
    author: 'Vicente Blasco Ibáñez',
    description: 'Novela antibélica ambientada en la Primera Guerra Mundial, bestseller mundial de 1916.',
    source: 'gutenberg',
    gutenbergId: 24536,
    librivoxAudioUrl: 'https://librivox.org/los-cuatro-jinetes-del-apocalipsis-by-vicente-blasco-ibanez/',
    librivoxSearchTitle: 'Cuatro Jinetes',
  },
  {
    title: 'La Isla del Tesoro',
    author: 'Robert Louis Stevenson',
    description: 'Clásico de aventuras piratas narrado por el joven Jim Hawkins en busca de un tesoro oculto.',
    source: 'gutenberg',
    gutenbergId: 45438,
    librivoxAudioUrl: 'https://librivox.org/la-isla-del-tesoro-by-robert-louis-stevenson/',
    librivoxSearchTitle: 'Isla del Tesoro',
  },
  {
    title: 'Viaje al Centro de la Tierra',
    author: 'Julio Verne',
    description: 'Novela de ciencia ficción en la que el profesor Lidenbrock y su sobrino descienden al interior de la Tierra.',
    source: 'wikisource',
    wikisourceTitle: 'Viaje al centro de la Tierra',
    librivoxAudioUrl: 'https://librivox.org/viaje-al-centro-de-la-tierra-by-jules-verne/',
  },
  {
    title: 'Romeo y Julieta',
    author: 'William Shakespeare',
    description: 'La más célebre tragedia de amor de la literatura universal.',
    source: 'wikisource',
    wikisourceTitle: 'Romeo y Julieta (Menéndez y Pelayo tr.)',
    librivoxAudioUrl: 'https://librivox.org/romeo-y-julieta-by-william-shakespeare/',
  },
  {
    title: 'Crimen y Castigo',
    author: 'Fiódor Dostoyevski',
    description: 'Novela psicológica sobre un estudiante que comete un crimen y lidia con su conciencia.',
    source: 'gutenberg',
    gutenbergId: 61851,
    librivoxAudioUrl: 'https://librivox.org/crimen-y-castigo-by-fyodor-dostoyevsky/',
  },
  {
    title: 'La Odisea',
    author: 'Homero',
    description: 'Epopeya griega sobre el largo viaje de Odiseo de regreso a Ítaca tras la guerra de Troya.',
    source: 'gutenberg',
    gutenbergId: 58221,
    librivoxAudioUrl: 'https://librivox.org/la-odisea-by-homero/',
    librivoxSearchTitle: 'Odisea',
  },
  {
    title: 'La Divina Comedia',
    author: 'Dante Alighieri',
    description: 'Poema épico medieval que narra el viaje de Dante por el Infierno, el Purgatorio y el Paraíso.',
    source: 'gutenberg',
    gutenbergId: 57303,
    librivoxAudioUrl: 'https://librivox.org/la-divina-comedia-by-dante-alighieri/',
    librivoxSearchTitle: 'Divina Comedia',
  },
  {
    title: 'Don Quijote de la Mancha — Vol. I',
    author: 'Miguel de Cervantes',
    description: 'Primera parte de la obra cumbre de la literatura española y universal.',
    source: 'gutenberg',
    gutenbergId: 2000,
    librivoxAudioUrl: 'https://librivox.org/don-quijote-vol-1-by-miguel-de-cervantes-saavedra/',
    librivoxSearchTitle: 'Don Quijote',
  },
  {
    title: 'Don Quijote de la Mancha — Vol. II',
    author: 'Miguel de Cervantes',
    description: 'Segunda parte de la inmortal novela del caballero manchego y su escudero Sancho Panza.',
    source: 'gutenberg',
    gutenbergId: 2000,
    librivoxAudioUrl: 'https://librivox.org/don-quijote-volume-2-by-miguel-de-cervantes-saavedra/',
    librivoxSearchTitle: 'Don Quijote',
  },
  {
    title: 'Orgullo y Prejuicio',
    author: 'Jane Austen',
    description: 'Novela de la escritora inglesa sobre el amor, el matrimonio y los prejuicios sociales en la Inglaterra del siglo XIX.',
    source: 'wikisource',
    wikisourceTitle: 'Orgullo y prejuicio',
    librivoxAudioUrl: 'https://librivox.org/orgullo-y-prejuicio1-by-jane-austen/',
    librivoxSearchTitle: 'Orgullo Prejuicio',
  },
  {
    title: 'Génesis',
    author: 'Anónimo',
    description: 'El primer libro del Antiguo Testamento: la creación del mundo, Adán y Eva, Noé, Abraham, Isaac, Jacob y José. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Génesis',
    librivoxAudioUrl: 'https://librivox.org/genesis-reina-valera-version/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Salmos',
    author: 'Anónimo',
    description: 'La gran colección de cánticos y oraciones del pueblo de Israel: 150 salmos de alabanza, lamento, gratitud y confianza en Dios. Versión Reina-Valera.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Salmos',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-antigua-19-salmos-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Mateo',
    author: 'Anónimo',
    description: 'El primer evangelio: la vida, enseñanzas, muerte y resurrección de Jesucristo, presentado como el Mesías prometido a Israel. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Mateo',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-01-mateo-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Juan',
    author: 'Anónimo',
    description: 'El cuarto evangelio, centrado en la divinidad de Jesús. Incluye Juan 3:16, los siete milagros y las declaraciones "Yo soy" de Cristo. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Juan',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-04-juan-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Romanos',
    author: 'Anónimo',
    description: 'La carta más sistemática de Pablo: la justificación por la fe, el poder del Espíritu y la vida cristiana en comunidad. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Romanos',
    librivoxAudioUrl: 'https://librivox.org/bible-nt-06-romanos-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Marcos',
    author: 'Anónimo',
    description: 'El evangelio más breve y dinámico: la vida de Jesús narrada con urgencia y acción, desde su bautismo hasta su resurrección. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Marcos',
    librivoxAudioUrl: 'https://librivox.org/el-bible-reina-valera-nt-02-evangelio-segun-marcos-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Lucas',
    author: 'Anónimo',
    description: 'El evangelio más extenso: relato detallado de la vida de Jesús, con especial énfasis en los pobres, las mujeres y la misericordia divina. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Lucas',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-03-lucas-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Hechos',
    author: 'Anónimo',
    description: 'La historia de la iglesia primitiva: el Espíritu Santo en Pentecostés, los apóstoles y los viajes misioneros de Pablo por el mundo mediterráneo. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Hechos',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-05-hechos-de-los-apostoles-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: '1 Corintios',
    author: 'Anónimo',
    description: 'La carta de Pablo a una iglesia dividida: unidad, el himno al amor, los dones espirituales y la resurrección de Cristo. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/1 Corintios',
    librivoxAudioUrl: 'https://librivox.org/1-corintios-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Efesios',
    author: 'Anónimo',
    description: 'Pablo describe la iglesia como cuerpo de Cristo: la gracia, la unidad entre judíos y gentiles, y la armadura de Dios. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Efesios',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-10-la-epistola-del-apostol-san-pablo-a-los-efesios-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Filipenses',
    author: 'Anónimo',
    description: 'La carta de la alegría: Pablo desde prisión anima a los creyentes a regocijarse en Cristo y a buscar la paz que sobrepasa todo entendimiento. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Filipenses',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-11-filipenses-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Hebreos',
    author: 'Anónimo',
    description: 'Jesús como sumo sacerdote eterno: argumentación teológica sobre la superioridad del nuevo pacto y el llamado a la fe perseverante. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Hebreos',
    librivoxAudioUrl: 'https://librivox.org/hebreos-version-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Santiago',
    author: 'Anónimo',
    description: 'Fe sin obras es muerta: enseñanza práctica sobre la vida cristiana, la sabiduría, la oración y el cuidado de los pobres. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Santiago',
    librivoxAudioUrl: 'https://librivox.org/carta-del-apostol-santiago-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Apocalipsis',
    author: 'Anónimo',
    description: 'La visión de Juan en Patmos: cartas a las siete iglesias, los sellos, las trompetas y la Nueva Jerusalén al final de los tiempos. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Apocalipsis',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-27-apocalipsis-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Éxodo',
    author: 'Anónimo',
    description: 'La liberación de Israel de Egipto: Moisés, las diez plagas, el paso del Mar Rojo y la entrega de los Diez Mandamientos en el Sinaí. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Éxodo',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-02-exodo-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Proverbios',
    author: 'Anónimo',
    description: '31 capítulos de sabiduría práctica atribuida a Salomón: consejos sobre la familia, el trabajo, la honestidad y el temor a Dios. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Proverbios',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-1909-20-libro-de-los-proverbios-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Isaías',
    author: 'Anónimo',
    description: 'El gran profeta del Antiguo Testamento: mensajes de juicio y restauración para Israel, y las profecías del Siervo Sufriente. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Isaías',
    librivoxAudioUrl: 'https://librivox.org/isaias-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },

  // ── Literatura Infantil ────────────────────────────────────────────────────

  {
    title: 'Fábulas y Verdades',
    author: 'Rafael Pombo',
    description:
      'La obra más querida del poeta colombiano: fábulas en verso para niños que incluyen El Renacuajo Paseador, Simón el Bobito, La Pobre Viejecita y Mirringa Mirronga. Dominio público.',
    source: 'wikisource',
    wikisourceTitles: [
      'El renacuajo paseador',
      'Simón el bobito',
      'La pobre viejecita',
      'Mirringa Mirronga',
      'El gato bandido',
      'Pastorcita',
      'Cutufato y su gato',
      'El búho y el palomo',
      'El niño y la mariposa',
      'La marrana peripuesta',
      'El coche',
    ],
    librivoxAudioUrl: 'https://librivox.org/fabulas-y-verdades-by-rafael-pombo/',
    coverUrl: '/covers/fabulas-pombo.png',
  },
  {
    title: 'Cuentos de la Selva',
    author: 'Horacio Quiroga',
    description:
      'Ocho cuentos para niños ambientados en la selva misionera: La Abeja Haragana, Las Medias de los Flamencos, La Tortuga Gigante y más. Obra hermana de los Cuentos de Amor ya disponibles en Noetia. Dominio público.',
    source: 'wikisource',
    wikisourceTitles: [
      'Cuentos de la selva/La tortuga gigante',
      'Cuentos de la selva/Las medias de los flamencos',
      'Cuentos de la selva/El loro pelado',
      'Cuentos de la selva/La guerra de los yacarés',
      'Cuentos de la selva/La abeja haragana',
      'Cuentos de la selva/Historia de dos cachorros de coatí y de dos cachorros de hombre',
      'Cuentos de la selva/La gama ciega',
      'Cuentos de la selva/El paso del Yabebirí',
    ],
    librivoxAudioUrl: 'https://librivox.org/cuentos-de-la-selva-para-los-ninos-by-horacio-quiroga/',
    librivoxSearchTitle: 'Cuentos de la Selva',
    coverUrl: '/covers/cuentos-selva.png',
  },
];
